version: 2

sources:
  - name: raw_gwz
    schema: gwz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez 
        columns:
          - name: date_date
            description: the date of purchase
        tests:
          - unique:
              column_name: "(orders_id|| '_' || pdt_id)"
        
      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            description: primary key of the table
            tests:
              - unique
              - not_null
      
      - name: adwords
        identifier: raw_gz_adwords
        columns:
          - name: campaign_key
            description: primary key of the table
            tests:
              - unique:
              - not_null:
                  
        

      - name: bing
        identifier: raw_gz_bing
        columns:
          - name: campaign_key
            description: primary key of the table
            tests:
              - unique:
              - not_null:
       
      - name: criteo
        identifier: raw_gz_criteo
        columns:
          - name: campaign_key
            description: primary key of the table
            tests:
              - unique:
              - not_null:
         
      - name: facebook
        identifier: raw_gz_facebook
        columns:
          - name: campaign_key
            description: primary key of the table
            tests:
              - unique:
              - not_null:
         
