version: 2

sources:
  - name: raw_gwz
    schema: gwz_raw_data
    description: greenweez raw data source
    tables:
      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
            description: primary key of the table
        tests:
              - unique:
              - not_null:
          

      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez 
        tests:
          - unique:
              column_name: "(orders_id || '-' || products_id)"
        
        columns:
          - name: date_date
            description: the date of purchase
        


      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            description: primary key of the table
        tests:
          - unique:
          - not_null:
              

